// Start Date: 2024-11-10 13:02 Europe/Paris
export const startDate = new Date(
    new Date(2024, 11 - 1, 10, 13, 2).toLocaleString('en-US', {
        timeZone: 'Europe/Paris',
    }),
);

// Start Location:
export const startLatLon = [46.4637857, -1.7951899];

export const reportsConfigurationDir = `${process.cwd()}/sync/ftp/reports/configuration/`;
export const reportsHistoryExcelDir = `${process.cwd()}/sync/ftp/reports/history/excel/`;
export const reportsHistoryPosreportDir = `${process.cwd()}/sync/ftp/reports/history/posreport/`;

// Few exception between boat IDs
// - boat26 => BEL207
// - boat1101 => JPN11
// - boat5005 => CHN5

export const boatsConfig = {
    BEL207: {
        skipper: 'Denis Van Weynbergh',
        skipperLink: 'https://www.vendeeglobe.org/skippers/denis-van-weynbergh',
        foiler: false,
        color: '#F3F4F8',
        colorFoil: '#DC6F3D',
        colorMiddle: '#000000',
        colorInside: '#E73223',
    },
    CHN5: {
        skipper: 'Jingkun Xu',
        skipperLink: 'https://www.vendeeglobe.org/skippers/jingkun-xu',
        foiler: true,
        color: '#D63232',
        colorFoil: '#DC6F3D',
        colorMiddle: '#0086EA',
        colorInside: '#98221E',
    },
    FRA01: {
        skipper: 'Violette Dorange',
        skipperLink: 'https://www.vendeeglobe.org/skippers/violette-dorange',
        foiler: false,
        color: '#FFFFFF',
        colorFoil: '#DC6F3D',
        colorMiddle: '#F5BF31',
        colorInside: '#080B10',
    },
    FRA08: {
        skipper: 'Justine Mettraux',
        skipperLink: 'https://www.vendeeglobe.org/skippers/justine-mettraux',
        foiler: true,
        color: '#0462A3',
        colorFoil: '#DC6F3D',
        colorMiddle: '#39444F',
        colorInside: '#F1F9FB',
    },
    FRA09: {
        skipper: 'Benjamin Dutreux',
        skipperLink: 'https://www.vendeeglobe.org/skippers/benjamin-dutreux',
        foiler: true,
        color: '#2B2B2B',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FFFFFF',
        colorInside: '#66CC33',
    },
    FRA10: {
        skipper: 'Romain Attanasio',
        skipperLink: 'https://www.vendeeglobe.org/skippers/romain-attanasio',
        foiler: true,
        color: '#2A528C',
        colorFoil: '#DC6F3D',
        colorMiddle: '#449BD4',
        colorInside: '#DA291C',
    },
    FRA100: {
        skipper: 'Sam Goodchild',
        skipperLink: 'https://www.vendeeglobe.org/skippers/sam-goodchild',
        foiler: true,
        color: '#4BA8A8',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FFFFFF',
        colorInside: '#246D6B',
    },
    FRA1000: {
        skipper: 'Tanguy Le Turquais',
        skipperLink: 'https://www.vendeeglobe.org/skippers/tanguy-le-turquais',
        foiler: false,
        color: '#8E214B',
        colorFoil: '#DC6F3D',
        colorMiddle: '#D9518F',
        colorInside: '#FFFFFF',
    },
    FRA109: {
        skipper: 'Samantha Davies',
        skipperLink: 'https://www.vendeeglobe.org/skippers/samantha-davies',
        foiler: true,
        color: '#8C1515',
        colorFoil: '#DC6F3D',
        colorMiddle: '#CE3232',
        colorInside: '#FFFFFF',
    },
    FRA112: {
        skipper: 'Sébastien Simon',
        skipperLink: 'https://www.vendeeglobe.org/skippers/sebastien-simon',
        foiler: true,
        color: '#12329A',
        colorFoil: '#FFFFFF',
        colorMiddle: '#4BA5DC',
        colorInside: '#E5DD45',
    },
    FRA13: {
        skipper: 'Damien Seguin',
        skipperLink: 'https://www.vendeeglobe.org/skippers/damien-seguin',
        foiler: true,
        color: '#AD182D',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FEFEFE',
        colorInside: '#3C3C3B',
    },
    FRA14: {
        skipper: 'Arnaud Boissières',
        skipperLink: 'https://www.vendeeglobe.org/skippers/arnaud-boissieres',
        foiler: true,
        color: '#FED13F',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FFFFFF',
        colorInside: '#0264B5',
    },
    FRA1461: {
        skipper: 'Antoine Cornic',
        skipperLink: 'https://www.vendeeglobe.org/skippers/antoine-cornic',
        foiler: false,
        color: '#385F89',
        colorFoil: '#DC6F3D',
        colorMiddle: '#09080D',
        colorInside: '#FFFFFF',
    },
    FRA15: {
        skipper: 'Clarisse Crémer',
        skipperLink: 'https://www.vendeeglobe.org/skippers/clarisse-cremer',
        foiler: true,
        color: '#001022',
        colorFoil: '#DC6F3D',
        colorMiddle: '#595959',
        colorInside: '#FDCD01',
    },
    FRA17: {
        skipper: 'Yannick Bestaven',
        skipperLink: 'https://www.vendeeglobe.org/skippers/yannick-bestaven',
        foiler: true,
        color: '#181A27',
        colorFoil: '#DC6F3D',
        colorMiddle: '#B00118',
        colorInside: '#FFFFFF',
    },
    FRA172: {
        skipper: 'Louis Duc',
        skipperLink: 'https://www.vendeeglobe.org/skippers/louis-duc',
        foiler: false,
        color: '#980D65',
        colorFoil: '#DC6F3D',
        colorMiddle: '#080B10',
        colorInside: '#FFFFFF',
    },
    FRA18: {
        skipper: 'Louis Burton',
        skipperLink: 'https://www.vendeeglobe.org/skippers/louis-burton',
        foiler: true,
        color: '#000000',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FED13F',
        colorInside: '#028C3B',
    },
    FRA2030: {
        skipper: 'Paul Meilhat',
        skipperLink: 'https://www.vendeeglobe.org/skippers/paul-meilhat',
        foiler: true,
        color: '#8BABC0',
        colorFoil: '#DC6F3D',
        colorMiddle: '#00639A',
        colorInside: '#00747D',
    },
    FRA22: {
        skipper: 'Guirec Soudée',
        skipperLink: 'https://www.vendeeglobe.org/skippers/guirec-soudee',
        foiler: false,
        color: '#FFFFFF',
        colorFoil: '#DC6F3D',
        colorMiddle: '#E66927',
        colorInside: '#1845B8',
    },
    FRA24: {
        skipper: 'Yoann Richomme',
        skipperLink: 'https://www.vendeeglobe.org/skippers/yoann-richomme',
        foiler: true,
        color: '#2535E0',
        colorFoil: '#DC6F3D',
        colorMiddle: '#D3262A',
        colorInside: '#FFFFFF',
    },
    FRA27: {
        skipper: 'Isabelle Joschke',
        skipperLink: 'https://www.vendeeglobe.org/skippers/isabelle-joschke',
        foiler: true,
        color: '#D3D3D3',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FFFFFF',
        colorInside: '#D13334',
    },
    FRA29: {
        skipper: 'Jean Le Cam',
        skipperLink: 'https://www.vendeeglobe.org/skippers/jean-le-cam',
        foiler: false,
        color: '#161616',
        colorFoil: '#DC6F3D',
        colorMiddle: '#3C3C3B',
        colorInside: '#E6C42B',
    },
    FRA3: {
        skipper: 'Jérémie Beyou',
        skipperLink: 'https://www.vendeeglobe.org/skippers/jeremie-beyou',
        foiler: true,
        color: '#181A27',
        colorFoil: '#DC6F3D',
        colorMiddle: '#A8A8A8',
        colorInside: '#CE3232',
    },
    FRA30: {
        skipper: 'Benjamin Ferré',
        skipperLink: 'https://www.vendeeglobe.org/skippers/benjamin-ferre',
        foiler: false,
        color: '#FFFFFF',
        colorFoil: '#DC6F3D',
        colorMiddle: '#123250',
        colorInside: '#FFEC33',
    },
    FRA5: {
        skipper: 'Éric Bellion',
        skipperLink: 'https://www.vendeeglobe.org/skippers/eric-bellion',
        foiler: false,
        color: '#2816B2',
        colorFoil: '#DC6F3D',
        colorMiddle: '#00141B',
        colorInside: '#BC1074',
    },
    FRA53: {
        skipper: 'Maxime Sorel',
        skipperLink: 'https://www.vendeeglobe.org/skippers/maxime-sorel',
        foiler: true,
        color: '#545454',
        colorFoil: '#DC6F3D',
        colorMiddle: '#D9D9D9',
        colorInside: '#2B2B2B',
    },
    FRA56: {
        skipper: 'Fabrice Amedeo',
        skipperLink: 'https://www.vendeeglobe.org/skippers/fabrice-amedeo',
        foiler: false,
        color: '#1D1E1C',
        colorFoil: '#DC6F3D',
        colorMiddle: '#449BD4',
        colorInside: '#FFFFFF',
    },
    FRA59: {
        skipper: 'Thomas Ruyant',
        skipperLink: 'https://www.vendeeglobe.org/skippers/thomas-ruyant',
        foiler: true,
        color: '#4BA7D3',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FEFEFE',
        colorInside: '#DB6E3D',
    },
    FRA71: {
        skipper: 'Manuel Cousin',
        skipperLink: 'https://www.vendeeglobe.org/skippers/manuel-cousin',
        foiler: false,
        color: '#0F1E3F',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FF8403',
        colorInside: '#FFFFFF',
    },
    FRA79: {
        skipper: 'Charlie Dalin',
        skipperLink: 'https://www.vendeeglobe.org/skippers/charlie-dalin',
        foiler: true,
        color: '#265BB2',
        colorFoil: '#DC6F3D',
        colorMiddle: '#D7D632',
        colorInside: '#FFFFFF',
    },
    FRA83: {
        skipper: 'Sébastien Marsset',
        skipperLink: 'https://www.vendeeglobe.org/skippers/sebastien-marsset',
        foiler: false,
        color: '#C55327',
        colorFoil: '#DC6F3D',
        colorMiddle: '#565655',
        colorInside: '#FFFFFF',
    },
    FRA85: {
        skipper: 'Nicolas Lunven',
        skipperLink: 'https://www.vendeeglobe.org/skippers/nicolas-lunven',
        foiler: true,
        color: '#98B747',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FFFFFF',
        colorInside: '#0DABD3',
    },
    GBR777: {
        skipper: 'Pip Hare',
        skipperLink: 'https://www.vendeeglobe.org/skippers/pip-hare',
        foiler: true,
        color: '#3E50C2',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FFFFFF',
        colorInside: '#080B10',
    },
    HUN23: {
        skipper: 'Szabolcs Weöres',
        skipperLink: 'https://www.vendeeglobe.org/skippers/szabolcs-weoeres',
        foiler: false,
        color: '#64BF71',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FF2F2B',
        colorInside: '#FCFCFC',
    },
    ITA34: {
        skipper: 'Giancarlo Pedote',
        skipperLink: 'https://www.vendeeglobe.org/skippers/giancarlo-pedote',
        foiler: true,
        color: '#FFFFFF',
        colorFoil: '#DC6F3D',
        colorMiddle: '#009246',
        colorInside: '#C6C6C6',
    },
    JPN11: {
        skipper: 'Kojiro Shiraishi',
        skipperLink: 'https://www.vendeeglobe.org/skippers/kojiro-shiraishi',
        foiler: true,
        color: '#D0D0D0',
        colorFoil: '#DC6F3D',
        colorMiddle: '#000000',
        colorInside: '#3C3C3B',
    },
    MON1297: {
        skipper: 'Boris Herrmann',
        skipperLink: 'https://www.vendeeglobe.org/skippers/boris-herrmann',
        foiler: true,
        color: '#A9A5A4',
        colorFoil: '#DC6F3D',
        colorMiddle: '#CC3030',
        colorInside: '#373737',
    },
    NZL64: {
        skipper: 'Conrad Colman',
        skipperLink: 'https://www.vendeeglobe.org/skippers/conrad-colman',
        foiler: false,
        color: '#F72E1A',
        colorFoil: '#DC6F3D',
        colorMiddle: '#33407F',
        colorInside: '#FFFFFF',
    },
    SUI49: {
        skipper: 'Oliver Heer',
        skipperLink: 'https://www.vendeeglobe.org/skippers/oliver-heer',
        foiler: false,
        color: '#F3F4F8',
        colorFoil: '#DC6F3D',
        colorMiddle: '#3E50C2',
        colorInside: '#D02E26',
    },
    SUI7: {
        skipper: 'Alan Roura',
        skipperLink: 'https://www.vendeeglobe.org/skippers/alan-roura',
        foiler: true,
        color: '#1A1A1A',
        colorFoil: '#DC6F3D',
        colorMiddle: '#FBE553',
        colorInside: '#000000',
    },
};
